[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "foundry-devops/=lib/foundry-devops/",
]
fs_permissions = [{ access = "read-write", path = "./" }]


[invariant]
runs = 3000
depth = 300
seed = 0x123
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
